from __future__ import annotations

from typing import Any


RUNNER_CATALOG: dict[str, dict[str, Any]] = {
    "server.cancellation-fixtures": {
        "repo": "server",
        "runner": "python_unittest",
        "nodes": ("tests.test_cancellation_handshake",),
        "timeout_seconds": 300,
        "minimum_tests": 17,
        "allowed_skips": 0,
    },
    "server.policy-fixtures": {
        "repo": "server",
        "runner": "python_unittest",
        "nodes": (
            "tests.test_worker_admin_routes.WorkerAdminRoutesTest.test_admin_plan_agent_config_keeps_only_canonical_review_worker_policy",
        ),
        "timeout_seconds": 300,
        "minimum_tests": 1,
        "allowed_skips": 0,
    },
    "server.progress-eta-fixtures": {
        "repo": "server",
        "runner": "python_unittest",
        "nodes": (
            "tests.test_worker_pull_routes.WorkerPullRoutesTest.test_worker_progress_records_worker_reported_phase_steps_message_and_log_summary",
            "tests.test_worker_pull_routes.WorkerPullRoutesTest.test_worker_eta_persists_and_batch_status_exposes_arbitrary_concurrency",
            "tests.test_worker_pull_routes.WorkerPullRoutesTest.test_worker_eta_rejects_invalid_numbers_ranges_and_terminal_payloads",
            "tests.test_worker_pull_routes.WorkerPullRoutesTest.test_worker_heartbeat_eta_is_persisted_and_terminal_result_clears_scan_eta",
            "tests.test_worker_pull_routes.WorkerPullRoutesTest.test_delayed_lower_sequence_event_cannot_overwrite_newer_scan_progress",
        ),
        "timeout_seconds": 300,
        "minimum_tests": 5,
        "allowed_skips": 0,
    },
    "server.result-fixtures": {
        "repo": "server",
        "runner": "python_unittest",
        "nodes": ("tests.test_review_worker_protocol_v1",),
        "timeout_seconds": 300,
        "minimum_tests": 28,
        "allowed_skips": 0,
    },
    "server.route-fixtures": {
        "repo": "server",
        "runner": "python_unittest",
        "nodes": ("tests.test_worker_pull_routes",),
        "timeout_seconds": 300,
        "minimum_tests": 123,
        "allowed_skips": 0,
    },
    "server.system-limit-fixtures": {
        "repo": "server",
        "runner": "python_unittest",
        "nodes": (
            "tests.test_configuration_contracts.ConfigurationContractsTest.test_review_phase_limits_are_global_admin_config",
        ),
        "timeout_seconds": 300,
        "minimum_tests": 1,
        "allowed_skips": 0,
    },
    "web.api-fixtures": {
        "repo": "web",
        "runner": "node_vitest",
        "nodes": ("src/api/pullwise.test.js",),
        "timeout_seconds": 300,
        "minimum_tests": 8,
        "allowed_skips": 0,
    },
    "web.flow-fixtures": {
        "repo": "web",
        "runner": "node_vitest",
        "nodes": ("src/screens/flow.test.jsx",),
        "timeout_seconds": 300,
        "minimum_tests": 75,
        "allowed_skips": 0,
    },
    "web.history-fixtures": {
        "repo": "web",
        "runner": "node_vitest",
        "nodes": ("src/screens/issues.test.jsx",),
        "timeout_seconds": 300,
        "minimum_tests": 69,
        "allowed_skips": 0,
    },
    "web.normalizer-fixtures": {
        "repo": "web",
        "runner": "node_vitest",
        "nodes": ("src/lib/pullwise-data.test.js",),
        "timeout_seconds": 300,
        "minimum_tests": 75,
        "allowed_skips": 0,
    },
    "web.progress-fixtures": {
        "repo": "web",
        "runner": "node_vitest",
        "nodes": ("src/components/scan-progress.test.jsx",),
        "timeout_seconds": 300,
        "minimum_tests": 1,
        "allowed_skips": 0,
    },
    "web.timing-fixtures": {
        "repo": "web",
        "runner": "node_vitest",
        "nodes": ("src/components/scan-timing.test.jsx",),
        "timeout_seconds": 300,
        "minimum_tests": 6,
        "allowed_skips": 0,
    },
    "worker.public-scan-canonical-fixture": {
        "repo": "worker",
        "runner": "node_script",
        "nodes": ("scripts/verify_public_scan_fixture.mjs",),
        "timeout_seconds": 60,
        "minimum_tests": 3,
        "allowed_skips": 0,
    },
    "worker.strict-v1-wire-canonical-fixture": {
        "repo": "worker",
        "runner": "python_script",
        "nodes": ("tests/test_agent_first_contract_wire_fixture.py",),
        "timeout_seconds": 60,
        "minimum_tests": 7,
        "allowed_skips": 0,
    },
}
